<?php

namespace frontend\components;

use common\helpers\RatingBadgeProvider;
use yii\helpers\Url;

class FullCompaniesRatingWidget extends CompaniesRatingWidget
{
    private $img_dir = "/frontend/web/mt/img/";

    /** @var RatingBadgeProvider */
    private $RatingBadgeProvider;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->RatingBadgeProvider = new RatingBadgeProvider();
    }


    public function run()
    {
        return $this->render("full-companies-rating-widget/view", ["items" => $this->items, "widget" => $this]);
    }

    public function getCompanyLink($alias)
    {
        return Url::toRoute(['main/company', 'alias'=>$alias]);
    }

    public function getLogoPath($item)
    {
        return $this->img_dir . $item['logo'];
    }

    /**
     * @param $regions
     * @param int $limit
     * @return string
     */
    public function getLimitedRegions($regions, $limit = 4)
    {
        if (!$regions) return "-";

        if (empty($regions)) return $regions;

        if (count($regions) <= $limit) return implode(", ", array_column($regions, "name"));

        return implode(", ", array_slice(array_column($regions, "name"), 0, $limit));
    }

    public function getBadgeLabel($item)
    {
        return $this->RatingBadgeProvider->getBadgeClass($item['rating_status']);
    }

    public function checkValue($value)
    {
        return empty($value) || !$value ? false : true;
    }
}
